### ISSUE TITLE
cannot import name 'MutableSequence' from 'collections'

### ISSUE THREAD

**Issue by GrimPixel** [ijgnd/anki21__editor_add_hyperlink#13]
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Mindmap from tag hierarchy⁩':
⁨Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aqt/addons.py", line 239, in loadAddons
    __import__(addon.dir_name)
  File "/home/grim/.local/share/Anki2/addons21/965278890/__init__.py", line 13, in <module>
    from .mindmap_creator_dialog import show as show_dialog
  File "/home/grim/.local/share/Anki2/addons21/965278890/mindmap_creator_dialog.py", line 12, in <module>
    from .libaddon.gui.dialog_webview import WebViewer
  File "/home/grim/.local/share/Anki2/addons21/965278890/libaddon/gui/dialog_webview.py", line 42, in <module>
    from .basic.dialog_basic import BasicDialog
  File "/home/grim/.local/share/Anki2/addons21/965278890/libaddon/gui/basic/dialog_basic.py", line 40, in <module>
    from .interface import CommonWidgetInterface
  File "/home/grim/.local/share/Anki2/addons21/965278890/libaddon/gui/basic/interface.py", line 48, in <module>
    from collections import MutableSequence, MutableSet, MutableMapping
ImportError: cannot import name 'MutableSequence' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
⁩

**Comment by ijgnd** [comment]
> **When loading '⁨Mindmap from tag hierarchy⁩':**

> File "/home/grim/.local/share/Anki2/addons21/**965278890**/init.py", line 13, in 

I have no idea how this is related to Add Hyperlink. Reopen this issue if the problem persists with all other add-ons disabled.

Also the answer is *probably* (afaik) in the last line: You are using python 3.10 whereas the official anki versions only use 3.9. So add-ons that use python features that were removed in python 3.10 still work for regular users but not for you ....

**Comment by GrimPixel** [comment]
Sorry, there were a lot of errors and I came to the wrong repo.
